import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { motion } from "framer-motion";
import Link from "next/link";
import Sign from "../svgs/sign";
import { PropsWithChildren } from "react";
import { useRouter } from "next/router";
import { useMediaQuery } from "@mui/material";

const Home: NextPage = () => {
  const matches = useMediaQuery("(min-width: 400px)")
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main className={styles.main}>
        <header className={styles.header}>
          <Image src={"/logo.svg"} width={100} height={100} />
          <div className={styles.icons}>
            <Link href="https://discord.com">
              <Image src={"/discord.svg"} width={100} height={100} />
            </Link>
            <Link href="https://twitter.com">
              <Image src={"/twitter.svg"} width={100} height={100} />
            </Link>
          </div>
        </header>

        <motion.section className={styles.gridSection}>
          <motion.div
            className={styles.mainIcon}
            animate={{ height: ["0vh", "100vh"], opacity: [0, 1] }}
          >
            <motion.div className={styles.splash}>
              <Image src={"/splash.svg"} width={100} height={1000} />
            </motion.div>
            <Image src={"/main.svg"} width={100} height={"1000"} />
          </motion.div>
          <motion.div
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <motion.div
              className={styles.lzyutes_text}
              animate={{
                transition: { delay: 2 },
                y: ["-40%", matches? "-30%":"0%"],
                opacity: [0, 0.2, 0.3, 1],
              }}
            >
              <Image src={"/lzyutes.svg"} height={1000} width={100} />
            </motion.div>
            <Sign className={styles.signPost}>
              <CustomLink href="" className={styles.links}></CustomLink>
              <CustomLink href="" className={styles.links}></CustomLink>
              <CustomLink href="" className={styles.links}></CustomLink>
            </Sign>
          </motion.div>
        </motion.section>
        {/* <Image src={"/avatar1.svg"} width={100} height={100} />
          <Image
            style={{ background: "" }}
            src={"/avatar4.svg"}
            width={100}
            height={"1000"}
          />
        <Image src={"/avatar2.svg"} width={100} height={100} />
        <Image src={"/avatar3.svg"} width={100} height={100} /> */}
      </motion.main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
};

const CustomLink = ({
  children,
  className,
  href,
}: PropsWithChildren & { className: string; href: string }) => {
  const router = useRouter();
  const route = () => {
    router.push(href);
  };
  return (
    <div onClick={route} className={className}>
      {children}
    </div>
  );
};
export default Home;
