import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/test.module.scss";
import { motion } from "framer-motion";
import  Main  from "../component/main";
// import { useMediaQuery } from "@mui/material";

const Home: NextPage = () => {
  // const matches = useMediaQuery("(min-width: 400px)")
  const [animate, setAnimate] = useState(false)
  return (
    <div 
      style={{ height: "100vh", position: "relative" }}
      className={styles.container}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.images}>
          <div className={styles.woman}>
            <Image src={"/avatar3.svg"} width={100} height={400} />
          <div className={styles.masked}>
            <Image src={"/masked.svg"} width={100} height={300} />
          </div>
          </div>
          <Main
          //  style={{position:animate?"absolute": "relative"}}
          />

        </div>
      </main>
    </div>
  );
};

export default Home;
